exclude: ^(.tox|doc|ci/templates|)(/|$)
repos:
  - repo: https://github.com/ambv/black
    rev: ca0dbb8fa6cca8c1fc2650cde9e71402c03a3324
    hooks:
      - id: black
        args:
          - '--safe'
          - '--quiet'
          - '--line-length=120'
        language_version: python3.10
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 08b4be84be2d74173246b7c9b6c22212a6c15a2d
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 32119baf69e913a72f2e1b1fbe0d56921b670ebb
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        files: inertia/
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]
  - repo: https://github.com/symonk/pre-commit-pdb-vars
    rev: 071c722d2b36924e30c998a415609176e247fce5
    hooks:
      - id: pdb-vars
#  - repo: https://github.com/hadialqattan/pycln
#    rev: v2.1.1
#    hooks:
#      - id: pycln
#        args: [--config=pyproject.toml, --all]
